### ISSUE TITLE
Tasks Lifecycle

### ISSUE THREAD

**Issue by lstrzebinczyk** [lstrzebinczyk/home_management_system#6]
**AC:**
- [ ] tasks in the list should render an icon on their left, depending on its state:
  - rectangle, if `pending`
  - half-filled rectangle, if `started`
  - filled rectangle, if `done`
- [ ] Pressing on a task name and its icon should cycle the task status:
  - `pending` -> `started`
  - `started` -> `done`
  - `done` -> `pending`
- [ ] Pressing on a task name should redirect to `/tasks` page
- [ ] If page shows any tasks in `done` status, it should render "Archive done tasks" button near the "New Task" button.
- [ ] Pressing `Archive done tasks` button should archive all tasks visible for current user in "done" state
- [ ] Archived tasks should not be visible

**TODO:**
- add mockups
